import Head from "next/head";

import { HomePage } from "@/components/HomePage/HomePage";
import { applyAppLayout } from "@/components/Layouts/AppLayout";
import { SetsHTTPAdapter } from "@/server/SetsHTTPAdapter";
import { http } from "@/server/http";

export default function Home({ sets }) {
  return (
    <>
      <Head>
        <title>PokeCollector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage sets={sets} />
    </>
  );
}

Home.getLayout = applyAppLayout;

export const getStaticProps = async () => ({
  props: { sets: await SetsHTTPAdapter(http).all() },
});
