import Head from "next/head";
import axios from "axios";

import { HomePage } from "../src/components/HomePage";
import { applyAppLayout } from "../src/components/AppLayout";

export default function Home({ sets }) {
  return (
    <>
      <Head>
        <title>PokeCollector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage sets={sets} />
    </>
  );
}

Home.getLayout = applyAppLayout;

export const getStaticProps = async () => {
  const sets = await axios
    .get("https://api.pokemontcg.io/v2/sets?orderBy=-releaseDate", {
      headers: { "X-Api-Key": process.env.API_KEY },
    })
    .then((res) => res.data.data);

  return {
    props: { sets: sets },
  };
};
